language: node_js
node_js:
 - 16

# before_install:
#   - npm i -g codacy-coverage
#   - npm i -g codecov

cache:
  directories:
    - node_modules

script:
  - npm run build
  # - npm run test:unit

# after_success:
#   - codecov
#   - cat coverage/lcov.info | codacy-coverage

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: dist
